# language: node_js removed due to https://github.com/travis-ci/travis-ci/issues/2311
os:
  - linux
  - osx

language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - openssl
env:
  global:
    - GCC_VERSION=4.8
  matrix:
  - TRAVIS_NODE_VERSION="0.8" LIBCURL_VERSION_TAG=LATEST
  - TRAVIS_NODE_VERSION="0.10" LIBCURL_VERSION_TAG=LATEST
  - TRAVIS_NODE_VERSION="0.12" LIBCURL_VERSION_TAG=LATEST
  - TRAVIS_NODE_VERSION="iojs-3" LIBCURL_VERSION_TAG=LATEST
  - TRAVIS_NODE_VERSION="4" LIBCURL_VERSION_TAG=LATEST
  # repeat again but for curl-7_35_0
  - TRAVIS_NODE_VERSION="0.8" LIBCURL_VERSION_TAG="curl-7_35_0"
  - TRAVIS_NODE_VERSION="0.10" LIBCURL_VERSION_TAG="curl-7_35_0"
  - TRAVIS_NODE_VERSION="0.12" LIBCURL_VERSION_TAG="curl-7_35_0"
  - TRAVIS_NODE_VERSION="iojs-3" LIBCURL_VERSION_TAG="curl-7_35_0"
  - TRAVIS_NODE_VERSION="4" LIBCURL_VERSION_TAG="curl-7_35_0"

matrix:
  allow_failures:
    - os: osx

cache:
  directories:
    - $HOME/curl-source

git:
  submodules: false

before_install:

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  # always use the latest npm
  - npm install npm
  - mv node_modules npm
  # https://github.com/travis-ci/travis-ci/issues/3668
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CC=/usr/bin/gcc-${GCC_VERSION} CXX=/usr/bin/g++-${GCC_VERSION} fi;
  - export PATH=$HOME/curl/bin:$PATH
  # output helpful info
  - node --version
  - npm/.bin/npm --version
  - gcc --version && g++ --version
  # grab libcurl
  - if [[ ${LIBCURL_VERSION_TAG} == 'LATEST' ]]; then
      TAG=$(git ls-remote --tags https://github.com/bagder/curl.git | awk '{print $2}' | grep "curl-" | grep -v "[0-9][_-][abp]" | grep -v "{" | sort -t_ -k 1.16,1n -k 2,2n -k 3,3n -k 4,4n | sed -n "s@.*\(curl-[0-9_]\)@\1@p" | tail -n1);
    else
      TAG=${LIBCURL_VERSION_TAG};
    fi;
  - mkdir -p $HOME/curl-source
  - cd $HOME/curl-source
  - if [[ ! -d "$TAG" ]]; then
      git clone --branch "$TAG" --depth 1 https://github.com/bagder/curl.git "$TAG";
    fi;
  - cd "$TAG"
  - ./buildconf && ./configure --prefix=$HOME/curl && make && make install
  - curl-config --version
  - curl-config --features
  - curl-config --protocols
  - cd $TRAVIS_BUILD_DIR
  - npm/.bin/npm install

script:
  - npm/.bin/npm test
