os:
  - linux
  - osx
# macos version
osx_image: xcode7.3
# linux dist
dist: trusty
language: node_js
node_js:
  - "8"
  - "10"
  - "11"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # Those are the defaults for trusty release on TravisCI
      - gcc-4.8
      - g++-4.8
      # - gcc-6
      # - g++-6
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "11"
env:
  global:
    - GCC_VERSION=4.8
    - DEBUG=node-libcurl
    - LIBSSH2_RELEASE=1.8.2
    - MACOSX_DEPLOYMENT_TARGET=10.12
    - secure: d64E8XbVGHuQ0kls1oVUF1y6pnj3iqZB34roKBHAFTyWBXReC1FWLb+qEShCJicUDkeK2At7vQUz7ohMn2mL/hVXiRbuSaYuDKFx8iDeei9mTgE+iy258mSovnNvXfG72EP5+LB+UOhgmTGe0qyTALOQ6ceCgjdscul3IGWE8lw=
  matrix:
    - LIBCURL_RELEASE=LATEST
    - LIBCURL_RELEASE=7_50_0

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
  yarn: true

git:
  depth: 10
  submodules: false

before_install:
  # Use latest yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      export CC="gcc-${GCC_VERSION}";
      export CXX="g++-${GCC_VERSION}";
      export LINK="gcc-${GCC_VERSION}";
      export LINKXX="g++-${GCC_VERSION}";
    fi
  # Update openssl on osx, and add it to the Path
  # When configuring openssl should we call ths directly?
  # PKG_CONFIG_PATH=/opt/OpenSSL/lib/pkgconfig ./configure --with-ssl
  # - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
  #     brew update;
  #     brew reinstall -s libtool;
  #     brew install openssl;
  #     brew outdated openssl || brew upgrade openssl;
  #     brew link --force openssl;
  #     export PATH=/usr/local/opt/openssl/bin:${PATH};
  #     export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig;
  #   fi
  - export PATH=$HOME/bin:$PATH
  - yarn --version
  - node --version
install: GIT_BRANCH=$TRAVIS_BRANCH GIT_COMMIT=$TRAVIS_COMMIT ./scripts/ci/build.sh
script: true
