# http://www.appveyor.com/docs/appveyor-yml
# mostly copied from nan appveyor.yml
os: Visual Studio 2015

environment:
  DEBUG: "node-libcurl"
  matrix:
    # node.js
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    # io.js
    - nodejs_version: 3
    # yay back to node again
    - nodejs_version: 4

platform:
  - x86
  - x64

# git clone depth
clone_depth: 5

# Install scripts. (runs after repo cloning)
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  # Update nodejs for versions < 1
  - IF %nodejs_version% LSS 1 npm -g install npm
  - IF %nodejs_version% LSS 1 set PATH=%APPDATA%\npm;%PATH%
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Install the package.
  - git submodule update --init --recursive
  - python deps\curl-for-windows\configure.py
  - npm install --loglevel=http

# Post-install test scripts.
test_script:
  # run tests
  - IF %nodejs_version% LSS 1 (npm test) ELSE (IF %nodejs_version% LSS 4 (iojs node_modules\mocha\bin\mocha test --reporter spec) ELSE (node node_modules\mocha\bin\mocha test --reporter spec))

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
