version: 2.1

executors:
  main:
    docker:
      - image: jonathancardoso/alpine-ci

orbs:
  build-addon-alpine-and-publish:
    jobs:
      build-addon:
        # https://circleci.com/docs/2.0/reusing-config/#parameter-syntax
        parameters:
          node-version:
            description: Version of Node.js
            type: string
          e:
            type: executor
          libcurl-version:
            type: string
          libidn2-version:
            type: string
            default: "2.1.1"
          libssh2-version:
            type: string
            default: "1.8.2"
          libunistring-version:
            type: string
            default: "0.9.10"
          nghttp2-version:
            type: string
          openssl-version:
            type: string
          zlib-version:
            type: string
            default: "1.2.11"
        executor: << parameters.e >>
        steps:
          - checkout
          - run: ln -s /usr/local/bin/node<<parameters.node-version>> /usr/local/bin/node
          - run:
              name: Setup Environment Variables
              command: |
                echo 'export LIBCURL_RELEASE="<< parameters.libcurl-version >>"' >> $BASH_ENV
                echo 'export LIBIDN2_RELEASE="<< parameters.libidn2-version >>"' >> $BASH_ENV
                echo 'export LIBSSH2_RELEASE="<< parameters.libssh2-version >>"' >> $BASH_ENV
                echo 'export LIBUNISTRING_RELEASE="<< parameters.libunistring-version >>"' >> $BASH_ENV
                echo 'export NGHTTP2_RELEASE="<< parameters.nghttp2-version >>"' >> $BASH_ENV
                echo 'export OPENSSL_RELEASE="<< parameters.openssl-version >>"' >> $BASH_ENV
                echo 'export ZLIB_RELEASE="<< parameters.zlib-version >>"' >> $BASH_ENV
          ####
          # Restore caches
          ###
          - run: echo "$LIBCURL_RELEASE - $LIBIDN2_RELEASE - $LIBSSH2_RELEASE - $LIBUNISTRING_RELEASE - $NGHTTP2_RELEASE - $OPENSSL_RELEASE - $ZLIB_RELEASE" > _libs_versions
          - restore_cache:
              key: v1-node<<parameters.node-version>>-deps-libs-{{ checksum "_libs_versions" }}
          ####
          # Build
          ####
          - run: GIT_TAG=$CIRCLE_TAG GIT_COMMIT=$CIRCLE_SHA1 ./scripts/ci/build.sh
          ####
          # Cache
          ####
          - save_cache:
              key: v1-node<<parameters.node-version>>-deps-libs-{{ checksum "_libs_versions" }}
              paths:
                - ~/deps/libcurl/build/<< parameters.libcurl-version >>
                - ~/deps/libssh2/build/<< parameters.libssh2-version >>
                - ~/deps/libidn2/build/<< parameters.libidn2-version >>
                - ~/deps/libunistring/build/<< parameters.libunistring-version >>
                - ~/deps/nghttp2/build/<< parameters.nghttp2-version >>
                - ~/deps/openssl/build/<< parameters.openssl-version >>
                - ~/deps/zlib/build/<< parameters.zlib-version >>

# Great docs
# https://circleci.com/docs/2.0/reusing-config/#getting-started-with-config-reuse

workflows:
  build-test-deploy:
    jobs:
      ####
      # Node 8
      ####
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-8-libcurl-latest
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "8"
          libcurl-version: "7.64.1"
          nghttp2-version: "1.33.0"
          openssl-version: "1.0.2r"
          e:
            name: main
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-8-libcurl-old
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "8"
          libcurl-version: "7.50.0"
          nghttp2-version: "1.33.0"
          openssl-version: "1.0.2r"
          e:
            name: main
      ####
      # Node 10
      ####
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-10-libcurl-latest
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "10"
          libcurl-version: "7.64.1"
          nghttp2-version: "1.34.0"
          openssl-version: "1.1.0j"
          e:
            name: main
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-10-libcurl-old
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "10"
          libcurl-version: "7.50.0"
          nghttp2-version: "1.34.0"
          openssl-version: "1.1.0j"
          e:
            name: main
      ####
      # Node 11
      ####
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-11-libcurl-latest
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "11"
          libcurl-version: "7.64.1"
          nghttp2-version: "1.37.0"
          openssl-version: "1.1.1b"
          e:
            name: main
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-11-libcurl-old
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "11"
          libcurl-version: "7.50.0"
          nghttp2-version: "1.37.0"
          openssl-version: "1.1.1b"
          e:
            name: main

