version: 2.1

executors:
  ubuntu:
    docker:
      - image: circleci/buildpack-deps:jessie-node-browsers
  main:
    docker:
      - image: jonathancardoso/alpine-ci

orbs:
  build-addon-alpine-and-publish:
    jobs:
      build-addon:
        # https://circleci.com/docs/2.0/reusing-config/#parameter-syntax
        parameters:
          node-version:
            description: Version of Node.js
            type: string
          electron-version:
            description: Version of Node.js
            default: ""
            type: string
          e:
            type: executor
            default: main
          brotli-version:
            type: string
            default: "1.0.7"
          libcurl-version:
            type: string
          libidn2-version:
            type: string
            default: "2.1.1"
          libssh2-version:
            type: string
            default: "1.8.2"
          libunistring-version:
            type: string
            default: "0.9.10"
          ncurses-version:
            type: string
            default: "6.1"
          nghttp2-version:
            type: string
          openldap-version:
            type: string
            default: "2.4.47"
          openssl-version:
            type: string
          zlib-version:
            type: string
            default: "1.2.11"
        executor: << parameters.e >>
        steps:
          - checkout
          - run: |
              [ -f /usr/local/bin/node<<parameters.node-version>> ] && ln -s /usr/local/bin/node<<parameters.node-version>> /usr/local/bin/node || true
          - run:
              name: Setup Environment Variables
              command: |
                echo 'export ELECTRON_VERSION="<< parameters.electron-version >>"' >> $BASH_ENV
                echo 'export BROTLI_RELEASE="<< parameters.brotli-version >>"' >> $BASH_ENV
                echo 'export LIBCURL_RELEASE="<< parameters.libcurl-version >>"' >> $BASH_ENV
                echo 'export LIBIDN2_RELEASE="<< parameters.libidn2-version >>"' >> $BASH_ENV
                echo 'export LIBSSH2_RELEASE="<< parameters.libssh2-version >>"' >> $BASH_ENV
                echo 'export LIBUNISTRING_RELEASE="<< parameters.libunistring-version >>"' >> $BASH_ENV
                echo 'export NCURSES_RELEASE="<< parameters.ncurses-version >>"' >> $BASH_ENV
                echo 'export NGHTTP2_RELEASE="<< parameters.nghttp2-version >>"' >> $BASH_ENV
                echo 'export OPENLDAP_RELEASE="<< parameters.openldap-version >>"' >> $BASH_ENV
                echo 'export OPENSSL_RELEASE="<< parameters.openssl-version >>"' >> $BASH_ENV
                echo 'export ZLIB_RELEASE="<< parameters.zlib-version >>"' >> $BASH_ENV
          ####
          # Restore caches
          ###
          - run:
              name: Create cache key file
              command: |
                echo "$BROTLI_RELEASE" >> _libs_versions
                echo "$LIBCURL_RELEASE" >> _libs_versions
                echo "$LIBIDN2_RELEASE" >> _libs_versions
                echo "$LIBSSH2_RELEASE" >> _libs_versions
                echo "$LIBUNISTRING_RELEASE" >> _libs_versions
                echo "$NCURSES_RELEASE" >> _libs_versions
                echo "$NGHTTP2_RELEASE" >> _libs_versions
                echo "$OPENLDAP_RELEASE" >> _libs_versions
                echo "$OPENSSL_RELEASE" >> _libs_versions
                echo "$ZLIB_RELEASE" >> _libs_versions
          - restore_cache:
              key: v1-nodeV<<parameters.node-version>>-electronV<<parameters.electron-version>>-deps-libs-{{ checksum "_libs_versions" }}
          ####
          # Build
          ####
          - run: GIT_TAG=$CIRCLE_TAG GIT_COMMIT=$CIRCLE_SHA1 ./scripts/ci/build.sh
          ####
          # Cache
          ####
          - save_cache:
              key: v1-nodeV<<parameters.node-version>>-electronV<<parameters.electron-version>>-deps-libs-{{ checksum "_libs_versions" }}
              paths:
                - ~/deps/brotli/build/<< parameters.brotli-version >>
                - ~/deps/libcurl/build/<< parameters.libcurl-version >>
                - ~/deps/libssh2/build/<< parameters.libssh2-version >>
                - ~/deps/libidn2/build/<< parameters.libidn2-version >>
                - ~/deps/libunistring/build/<< parameters.libunistring-version >>
                - ~/deps/ncurses/build/<< parameters.ncurses-version >>
                - ~/deps/nghttp2/build/<< parameters.nghttp2-version >>
                - ~/deps/openldap/build/<< parameters.openldap-version >>
                - ~/deps/openssl/build/<< parameters.openssl-version >>
                - ~/deps/zlib/build/<< parameters.zlib-version >>

# Great docs
# https://circleci.com/docs/2.0/reusing-config/#getting-started-with-config-reuse

workflows:
  build-test-deploy:
    jobs:
      ####
      # Node 8
      ####
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-8-libcurl-latest
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "8"
          libcurl-version: "7.64.1"
          nghttp2-version: "1.33.0"
          openssl-version: "1.0.2r"
          e:
            name: main
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-8-libcurl-old
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "8"
          libcurl-version: "7.50.0"
          nghttp2-version: "1.33.0"
          openssl-version: "1.0.2r"
          e:
            name: main
      ####
      # Node 10
      ####
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-10-libcurl-latest
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "10"
          libcurl-version: "7.64.1"
          nghttp2-version: "1.34.0"
          openssl-version: "1.1.0j"
          e:
            name: main
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-10-libcurl-old
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "10"
          libcurl-version: "7.50.0"
          nghttp2-version: "1.34.0"
          openssl-version: "1.1.0j"
          e:
            name: main
      ####
      # Node 12
      ####
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-12-libcurl-latest
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "12"
          libcurl-version: "7.64.1"
          nghttp2-version: "1.38.0"
          openssl-version: "1.1.1b"
          e:
            name: main
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-node-12-libcurl-old
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "12"
          libcurl-version: "7.50.0"
          nghttp2-version: "1.38.0"
          openssl-version: "1.1.1b"
          e:
            name: main
      ####
      # Electron v5
      ####
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-electron-v5-libcurl-latest
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "12"
          electron-version: "5.0.1"
          libcurl-version: "7.64.1"
          nghttp2-version: "1.38.0"
          openssl-version: "1.1.1b"
          e:
            name: ubuntu
      ####
      # Electron v4
      ####
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-electron-v4-libcurl-latest
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "12"
          electron-version: "4.2.0"
          libcurl-version: "7.64.1"
          nghttp2-version: "1.38.0"
          openssl-version: "1.1.1b"
          e:
            name: ubuntu
      ####
      # Electron v3
      ####
      - build-addon-alpine-and-publish/build-addon:
          name: build-addon-electron-v3-libcurl-latest
          context: general
          filters:
            tags:
              only: /^v.*/
          node-version: "12"
          electron-version: "3.1.9"
          libcurl-version: "7.64.1"
          nghttp2-version: "1.38.0"
          openssl-version: "1.1.1b"
          e:
            name: ubuntu

