name: build-and-release-macos

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop

strategy:
  matrix:
    node:
      - 12
      - 14
      - 15
    include:
      - node: 14
        libcurl-release: 7.73.0
        electron-version: 12.0.0
      - node: 14
        libcurl-release: 7.73.0
        electron-version: 11.2.3
      - node: 14
        libcurl-release: 7.73.0
        electron-version: 10.1.0
      - node: 14
        libcurl-release: 7.73.0
        electron-version: 9.3.3
      - node: 14
        libcurl-release: 7.73.0
        electron-version: 8.5.3
      - node: 14
        libcurl-release: 7.73.0
        nwjs-version: 0.52.0
      - node: 14
        libcurl-release: 7.73.0
        nwjs-version: 0.51.2
      - node: 14
        libcurl-release: 7.73.0
        nwjs-version: 0.49.2

env:
  LIBCURL_RELEASE: ${{ matrix.libcurl-release }}
  ELECTRON_VERSION: ${{ matrix.electron-version }}
  NWJS_VERSION: ${{ matrix.nwjs-version }}
  NODE_LIBCURL_GITHUB_TOKEN: ${{ secrets.NODE_LIBCURL_GITHUB_TOKEN }}

jobs:
  build-and-release-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Output yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore Yarn Cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: v1-${{ runner.os }}-yarn-cache-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-${{ runner.os }}-yarn-cache-${{ github.ref }}-
            v1-${{ runner.os }}-yarn-cache-
      - name: Restore libcurl deps cache
        uses: actions/cache@v2
        id: libcurl-deps-cache
        with:
          path: |
            ~/.node-gyp
            ~/deps
          key: v1-${{ runner.os }}-libcurl-deps-cache
          restore-keys: |
            v1-${{ runner.os }}-libcurl-deps-cache
      - name: 'Set GIT_TAG'
        if: startsWith(github.ref, 'refs/tags')
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: 'Publish Binary'
        run: |
          GIT_COMMIT=${{ github.sha }} ./scripts/ci/build.sh
